### PR TITLE
fix(chat): offline msgs order

### LINKED ISSUE #4733: Message reactions and edits
If i send a message while the other user is offline and i attach a reaction to it (or edit a msg), sometimes the latter wont appear on the other user.

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- Fix the offline message communication order so that reactions and edits wont be lost or overwritten

### Which issue(s) this PR fixes 🔨
- Resolve #4733 

### Additional comments 🎤
 After this we can merge #4755 too

### CODE REVIEW

File: libraries/Iridium/chat/ChatManager.ts [hunk 1]
```diff
@@ -146,28 +145,44 @@ export default class ChatManager extends Emitter<ConversationMessage> {
...
-            'iridium/chatmanager',
-            'sync/fetch/message - emitting synced message',
-            message,
+
+    // read msg infos in order
+    const msgs = await Promise.all(
+      message.payload.body.messages
+        .sort((a, b) => a.createdAt - b.createdAt)
+        .map(async (message) => {
+          const stored = await iridium.connector?.dag.get(
```
Comment (aewing) [inline libraries/Iridium/chat/ChatManager.ts:154]: I think we can use iridium.load and skip the manual decryption step

**Review by aewing — APPROVED** [review]
🛳

File: libraries/Iridium/chat/ChatManager.ts (hunk 1 above)
Comment (molimauro) [reply libraries/Iridium/chat/ChatManager.ts:154]: for some reasons the `await iridium.connector?.load(msg.cid)` fails:

image

Comment (molimauro) [reply libraries/Iridium/chat/ChatManager.ts:154]: thats because on iridium it loads this:

image

we should have object.body instead, where is the error? on core when storing the message?

**Comment by WanderingHogan** [comment]
I am seeing weird issues where the offline messages don't come in consistently, or they will show up, then on reload they dissapear. Do you think this should be looked at in a follow up pr? Or maybe it works with your edit message pr, i will check that out now

**Comment by molimauro** [comment]
Those should not be related to these PRs, are you experiencing the same on dev?

**Comment by phillsatellite** [comment]
@molimauro I also tested this one as well and wanted to leave a little note of my findings. I was able to add friends and send messages from both sides and still not receive them on either side 

https://user-images.githubusercontent.com/93608357/190226569-1bb16f07-222a-4020-a99d-f6fd99f3cf80.mov

**Comment by molimauro** [comment]
@phillsatellite i tried and they worked on my side, i dont think those inconsistencies are related to this PR honestly

**Comment by aewing** [comment]
I think the inconsistency should be addressed in my branch. if not I will follow up on this.

File: libraries/Iridium/chat/ChatManager.ts (hunk 1 above)
Comment (aewing) [reply libraries/Iridium/chat/ChatManager.ts:154]: ok, maybe something about the structure of the payload. I'll take a look in a followup.

**Review by aewing — APPROVED** [review]
