### PR TITLE
fix(requests): stop outgoing friend request names sometimes being dis…

### LINKED ISSUE #4607: Outgoing friend requests doesn't have friendly name, sometimes

### PR DESCRIPTION
**Pull request by nathan-power**
…played as did

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

Resolve #4607 

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

File: components/views/friends/friend/Friend.vue [hunk 1]
```diff
@@ -75,7 +75,7 @@ export default Vue.extend({
   methods: {
     async createFriendRequest() {
       this.loading = true
-      await iridium.friends?.requestCreate(this.user.did)
+      await iridium.friends?.requestCreate(this.user.did, false, this.user)
```
Comment (josephmcg) [inline components/views/friends/friend/Friend.vue:78]: i think we can reduce redundancy on props, only pass user instead of user.did and user

Comment (nathan-power) [reply components/views/friends/friend/Friend.vue]: Done

**Review by josephmcg — APPROVED** [review]
