### PR TITLE
fix(audio): talking indicator timeout

### LINKED ISSUE #4673: Fix voice indicator timeout

### PR DESCRIPTION
**Pull request by jasonwoodland**
**What this PR does** 📖
- Rewrite timeout logic for talking indicator

**Which issue(s) this PR fixes** 🔨

Resolve #4673 

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

File: utilities/AudioStreamUtils.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { AudioState } from '~/store/audio/types'
 
-const IS_TALKING_SENSITIVITY = 10 // %
-const TALKING_OFF_DELAY = 500 // ms
+const IS_TALKING_THRESHOLD = 20 // %
```
Comment (aewing) [inline utilities/AudioStreamUtils.ts:3]: would be cool if this was a user-controlled setting

Comment (WanderingHogan) [reply utilities/AudioStreamUtils.ts:3]: added this into the backlog project

**Review by WanderingHogan — APPROVED** [review]
